version: "3.9"

services:

  reverse-proxy:
    image: nginx:alpine
    container_name: amtemeterai-reverse-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: amtemeterai-frontend:v4
    container_name: amtemeterai-frontend
    restart: always

  api:
    build:
      context: ./backend/amtemeterai.Api
      dockerfile: Dockerfile
    image: amtemeterai-api:v4
    container_name: amtemeterai-api
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # Injected from .env
      ConnectionStrings__DefaultConnection: Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      Jwt__Key: ${JWT_SECRET}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      App__PublicBaseUrl: ${PUBLIC_BASE_URL}

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: amtemeterai-postgres
    restart: always
    environment:
      # Injected from .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: