// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amtemeterai.Api.Data;

#nullable disable

namespace amtemeterai.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430120637_RemoveUnusedDeliveryID")]
    partial class RemoveUnusedDeliveryID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("amtemeterai.Api.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("amtemeterai.Api.Models.DeliveryHeader", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryRemarks")
                        .HasColumnType("text");

                    b.Property<bool>("Invoiced")
                        .HasColumnType("boolean");

                    b.Property<bool>("Received")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("ReceiverToken")
                        .HasColumnType("uuid");

                    b.HasKey("DeliveryID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("DeliveryNumber")
                        .IsUnique();

                    b.ToTable("DeliveryHeaders");
                });

            modelBuilder.Entity("amtemeterai.Api.Models.DeliveryLine", b =>
                {
                    b.Property<int>("DeliveryLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryLineID"));

                    b.Property<int>("DeliveryHeaderDeliveryID")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryLineNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PackQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PackQuantityDelivered")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PackQuantityRejected")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PackQuantityReturned")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PackUOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SalesQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SalesUOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeliveryLineID");

                    b.HasIndex("DeliveryHeaderDeliveryID");

                    b.ToTable("DeliveryLines");
                });

            modelBuilder.Entity("amtemeterai.Api.Models.DeliveryHeader", b =>
                {
                    b.HasOne("amtemeterai.Api.Models.Customer", "Customer")
                        .WithMany("Deliveries")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("amtemeterai.Api.Models.DeliveryLine", b =>
                {
                    b.HasOne("amtemeterai.Api.Models.DeliveryHeader", "DeliveryHeader")
                        .WithMany("Lines")
                        .HasForeignKey("DeliveryHeaderDeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryHeader");
                });

            modelBuilder.Entity("amtemeterai.Api.Models.Customer", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("amtemeterai.Api.Models.DeliveryHeader", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
